export const getScreens = (doc = document) => ({
  start: doc.getElementById('start-screen'),
  quiz: doc.getElementById('quiz-screen'),
  result: doc.getElementById('result-screen'),
  settings: doc.getElementById('settings-screen'),
  stats: doc.getElementById('stats-screen'),
});

export const getElements = (doc = document) => ({
  version: doc.getElementById('app-version'),
  menuButton: doc.getElementById('menu-button'),
  menuPanel: doc.getElementById('menu-panel'),
  menuSettings: doc.getElementById('open-settings'),
  closeSettings: doc.getElementById('close-settings'),
  authAvatar: doc.getElementById('auth-avatar'),
  authAvatarFallback: doc.getElementById('auth-avatar-fallback'),
  authLogin: doc.getElementById('auth-login'),
  authLogout: doc.getElementById('auth-logout'),
  authMessage: doc.getElementById('auth-message'),
  questionCount: doc.getElementById('question-count'),
  questionMode20: doc.getElementById('question-mode-20'),
  questionModeWeak5: doc.getElementById('question-mode-weak5'),
  hintType: doc.getElementById('hint-type'),
  displayMode: doc.getElementById('display-mode'),
  orderNormal: doc.getElementById('order-normal'),
  orderReverse: doc.getElementById('order-reverse'),
  colorButtons: doc.querySelectorAll('.color-button'),
  progressText: doc.getElementById('progress-text'),
  progressBar: doc.getElementById('progress-bar'),
  elapsedTime: doc.getElementById('elapsed-time'),
  measureTimeToggle: doc.getElementById('measure-time-toggle'),
  kimariji: doc.getElementById('kimariji'),
  mainDisplayLabel: doc.getElementById('main-display-label'),
  toggleKimariji: doc.getElementById('toggle-kimariji'),
  options: doc.querySelectorAll('#options-container .option-button'),
  feedback: doc.getElementById('feedback'),
  autoAdvanceProgress: doc.getElementById('auto-advance-progress'),
  autoAdvanceBar: doc.querySelector('.auto-advance-bar'),
  selectedColorLabel: doc.getElementById('selected-color-label'),
  cancelQuiz: doc.getElementById('cancel-quiz'),
  nextQuestion: doc.getElementById('next-question'),
  resultCount: doc.getElementById('result-count'),
  resultRate: doc.getElementById('result-rate'),
  resultComment: doc.getElementById('result-comment'),
  resultList: doc.getElementById('result-list'),
  retrySame: doc.getElementById('retry-same'),
  retryIncorrect: doc.getElementById('retry-incorrect'),
  chooseColor: doc.getElementById('choose-color'),
  giveUp: doc.getElementById('give-up-button'),
  viewStats: doc.getElementById('view-stats'),
  viewStatsFromResult: doc.getElementById('view-stats-from-result'),
  closeStats: doc.getElementById('close-stats'),
  clearHistory: doc.getElementById('clear-history'),
  totalQuizzes: doc.getElementById('total-quizzes'),
  totalQuestions: doc.getElementById('total-questions'),
  totalCorrect: doc.getElementById('total-correct'),
  overallAccuracy: doc.getElementById('overall-accuracy'),
  overallHintUsage: doc.getElementById('overall-hint-usage'),
  colorStatsBody: doc.getElementById('color-stats-tbody'),
  recentActivity: doc.getElementById('recent-activity'),
  statsFilterNormal: doc.getElementById('stats-filter-normal'),
  statsFilterReverse: doc.getElementById('stats-filter-reverse'),
});
